name: 📦 Build Flatpak

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  flatpak:
    name: build-flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Flatpak
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
        with:
          build-bundle:  false
          manifest-path: com.DaRealRoyal.TacticalMathReturns.yml
          cache-key: flatpak-builder-${{ github.sha }}
          branch: stable
      - name: Deploy
        if: github.event_name != 'pull_request'
        uses: flatpak/flatpak-github-actions/flat-manager@v6
        with:
          repository: ""
          flat-manager-url: https://flatpak.alya.nils.moe
          token: ${{ secrets.FLATMAN_TOKEN }}

